conversation: {}

# The Hugging Face model name of the base model.
base_model: accounts/fireworks/models/llama-v3p1-70b-instruct

# adjust hyperparameters
epochs: 2
lora_rank: 32
learning_rate: 0.0002
